---
title: Rebecca Li
timezone: UTC
description: 'post-modern roboticist
'

permalink: ":title/"
baseurl: ''
url: htttp://rebecca.li
author: Rebecca Li
author-img: og-image.jpg
about-author: Post-modern Roboticist
github: rebeccali
# email: rebecca@mit.edu
# safe: false
discus-identifier: rebeccali
analytics:
markdown: kramdown
plugins_dir:
- _plugins
- jekyll-sitemap
- jekyll-paginate-v2
- jekyll-gallery-generator
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  # collection: 'posts'

  sort_field: 'date'
  sort_reverse: 'true'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10

paginate_path: "/page/:num"
exclude:
- node_modules
- gulpfile.js
- package.json
- yarn.lock
gallery:
  dir: photography
  symlink: false
  title: Photography
  title_prefix: 'Photography: '
  sort_field: date_time
  thumbnail_size:
    x: 400
    y: 400
  galleries:
    random:
      best_image: cows.png
      info:
        desc: UnsortedImages, 2017. Copyright Rebecca Li.
    neerja:
      best_image: large-LYC_5995.png
      info:
        desc: My friend Neerja. Copyright Rebecca Li.
    iceland:
      best_image: chair.jpg
      info:
        desc: Iceland, 2017. Copyright Rebecca Li.
    central_park:
      best_image: bigbird.jpg
      info:
        desc: Central Park, 2017. Copyright Rebecca Li.
    tiny_studio:
      best_image: big.jpg
      info:
        desc: Tiny flower studio, 2018. Copyright Rebecca Li.
